export const PODCAST_SEARCH_REQUEST = "PODCAST_SEARCH_REQUEST";
export const PODCAST_SEARCH_SUCCESS = "PODCAST_SEARCH_SUCCESS";
export const PODCAST_SEARCH_FAILURE = "PODCAST_SEARCH_FAILURE";
export const PODCAST_SEARCH_RESET = "PODCAST_SEARCH_RESET";