/*
export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
*/

export const PDF_SEARCH_REQUEST = "PDF_SEARCH_REQUEST";
export const PDF_SEARCH_SUCCESS = "PDF_SEARCH_SUCCESS";
export const PDF_SEARCH_FAILURE = "PDF_SEARCH_FAILURE";
export const PDF_SEARCH_RESET = "PDF_SEARCH_RESET";


