export const VIDEO_SEARCH_REQUEST = "VIDEO_SEARCH_REQUEST";
export const VIDEO_SEARCH_SUCCESS = "VIDEO_SEARCH_SUCCESS";
export const VIDEO_SEARCH_FAILURE = "VIDEO_SEARCH_FAILURE";
export const VIDEO_SEARCH_RESET = "VIDEO_SEARCH_RESET";